// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLOGyWRmOY6ZOF1Z9EaBw1ru8fyF7sdQg',
    appId: '1:355737236784:web:a3f5b3a186616d81cf04f5',
    messagingSenderId: '355737236784',
    projectId: 'chatapp-748fe',
    authDomain: 'chatapp-748fe.firebaseapp.com',
    storageBucket: 'chatapp-748fe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw6VyyIkCJnowIqmkKkmkhmBw7zp9HvGg',
    appId: '1:355737236784:android:f70af204b6513cdecf04f5',
    messagingSenderId: '355737236784',
    projectId: 'chatapp-748fe',
    storageBucket: 'chatapp-748fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXSn3DicVysZlxIwTZbPa7jHb1rYHb0h0',
    appId: '1:355737236784:ios:826694a1715709facf04f5',
    messagingSenderId: '355737236784',
    projectId: 'chatapp-748fe',
    storageBucket: 'chatapp-748fe.appspot.com',
    iosClientId: '355737236784-qlqa6eu79pttce7iu7gvga1mgejc8j56.apps.googleusercontent.com',
    iosBundleId: 'com.example.gptbrycen',
  );
}
